name: Deploy to Infomaniak (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          ssh_private_key: ''
          local_path: './HTLM/*'
          remote_path: '/sites/nr-works.ch/'
          sftp_only: true
          rsyncArgs: '-avzr --exclude=*.rtf'
