name: Deploy to Infomaniak (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./HTLM/
          server-dir: ./
          exclude: |
            **/*.rtf
